### ISSUE TITLE
[FEATURE]: Dynamic resize of the window

### ISSUE THREAD

**Issue by k5tQp2ET** [MissCorruption/QuickLootIE#12]
### Motivation

Nice indicator there is little items insdie.

### Feature Description

Like in this mod, https://www.nexusmods.com/skyrimspecialedition/mods/80516. Basicly when there is one item window is small.

**Comment by MissCorruption** [comment]
Progress towards this [has been made](https://github.com/MissCorruption/QuickLootEE-NG/commit/bcff286b4a2fd8aca778c7e1169796bf76e7c113), but getting the shapes into the LootMenu is troublesome in CS6. While I could do it in JPEX, that wouldn't properly reflect on Github

**Comment by MissCorruption** [comment]
Implemented with [d4c39c8](https://github.com/MissCorruption/QuickLootIE/commit/d4c39c895ca4e373f02f72793d2a16826b81e035)
