### ISSUE TITLE
[FEATURE]: LootMenu scaling based on slider

### ISSUE THREAD

**Issue by MissCorruption** [MissCorruption/QuickLootIE#21]
### Feature Title

LootMenu scaling based on slider

### Feature Description

The current implementation in [LootMenu.h](https://github.com/MissCorruption/QuickLootIE/blob/master/src/Scaleform/LootMenu.h#L323-L347) is broken and doesn't adjust the menu size.

Here are references for X/Y scaling and a slider:

1. https://github.com/Scrabx3/S.L.U.T.S.Resume/blob/d6558df436d82a72b3a6a7fa12355e01cfeb3d67/Source/Scripts/SlutsMissionHaulHUD.psc#L41

2. https://github.com/Scrabx3/SLUTS-MissionHaulHUD/blob/29f959449d7402b6e1f9fe990e11c6007a3e0b70/PilferageMeter.as#L44

**Comment by AtomCrafty** [comment]
This can be closed.
