### ISSUE TITLE
[FEATURE]: Recognize ButtonArtDD.swf and use it if required

### ISSUE THREAD

**Issue by Wuerfelhusten** [MissCorruption/QuickLootIE#31]
### Feature Title

Recognize ButtonArtDD.swf and use it if required

### Motivation

Pretty much all UIs that are based on Dear Diary Dark Mode use a ButtonArtDD.swf file instead of a Buttonart.swf file. 
If, like me, you are about to create an Untarnished UI patch, you will immediately notice that the buttonarts from Untarnished UI have not been adopted. The whole thing can be workarounded by packing a duplicate of the DDDM version of the buttonart renamed to "Buttonart.swf".

### Feature Description

It would be very neat for different reskins if the interface used either the Buttonart.swf, as before, or the ButonartDD.swf, if it exists

**Comment by AtomCrafty** [comment]
I don't think the official skin needs to be changed for that. The reskinned swf just needs to specify a different ButtonArt import path. I've created a DDDM reskin for testing purposes and that worked without issues.

![image](https://github.com/MissCorruption/QuickLootIE/assets/4553050/0aca4187-ff89-43b3-ba20-ff4064eb50b5)

**Comment by AtomCrafty** [comment]
I'm planning to create a more in-depth reskinning guide at some point, but the swf is still subject to change, so I'd hold off with reskins until that is finalized :)

**Comment by MissCorruption** [comment]
In JPEX you'd find the import URL here:
![image](https://github.com/MissCorruption/QuickLootIE/assets/125442561/1146524a-6309-43a4-a6cd-0f980931d0cb)
Adjusting that to `ButtonArtDD.swf ` should work fine

**Comment by Wuerfelhusten** [comment]
Well, nevermind, something was not working in my program. I was searching for those ImportAssets but did not find them. Thanks for the help. "Others" Folder was somehow disabled on my end.
