### ISSUE TITLE
[FEATURE]: Renaming the SWF File

### ISSUE THREAD

**Issue by Wuerfelhusten** [MissCorruption/QuickLootIE#33]
### Feature Title

Renaming the SWF File

### Motivation

There are several versions of Quickloot. The legacy version, Quickloot RE, Quieloot EE and now also Quickloot IE. All use the same interface file (at least in terms of name). This is not a bad thing in principle, but in plain language it also means that a NORDIC UI patch for Quickloot RE is installed by some inexperienced users via Quickloot IE. Unfortunately, this leads to unnecessary support cases and is somewhat confusing.

### Feature Description

My suggestion here would be to rename the interface file to something else. This way no patch for another Quickloot version overwrites the interface of Quickloot IE and vice versa. This makes more than sense, especially with the upcoming major changes.

### Additional Context

Credits for the idea: [Rename Oxygenmeter.swf to OxygenMeter2.swf](https://www.nexusmods.com/skyrimspecialedition/mods/64532) to avoid a downgrade by existing patches.
[image](https://github.com/MissCorruption/QuickLootIE/assets/128251181/df50ec52-c812-4db0-8a05-e0336afef387)

**Comment by AtomCrafty** [comment]
That sounds like a good idea to me. It has the potential to avoid a lot of unnecessary confusion regarding old, incompatible reskins. We could even still check for the old file name and show a warning that it's incompatible.

**Comment by MissCorruption** [comment]
Given that using an old Lootmenu might break things, I'd rename it personally. This is the simplest solution and probably the easiest to support, given my experience with end users and reading
