### ISSUE TITLE
[Bug]: LootMenu may fail to display

### ISSUE THREAD

**Issue by MissCorruption** [MissCorruption/QuickLootIE#35]
### What happened?

Occasionally, the LootMenu won't display, but will still react to inputs. Opening the container with Q, nor a game restart fixes it, as it seems to be "save-wide". Cause is currently unknown. This occurred with the canary release.

### Version

1.1.0

### What Skyrim version are you using?

1.6.1170

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AtomCrafty** [comment]
This should be fixed now. It was an issue with the MCM settings not initializing correctly, so some variables like scale were 0.
