### ISSUE TITLE
[Bug]: NPC owned item not correctly shown (Mod version 1.2.0)

### ISSUE THREAD

**Issue by VolkovChitzkoi** [MissCorruption/QuickLootIE#36]
### What happened?

Pratically I have started the game, chose to go with Ralof and arrived in his sister house. When i check the loot in the furnitures, I have seen that the entries presented was all white, but checking them with the normal way (normal interface with SkyUI), there was some red hand symbols around some items that got presented me with a white name. Going inside the Sleeping giant and checking the Delphine chest, shown me all red entries. I don't know if there's known conflict with QuickLoot, but there shouldn't be.

### Version

1.1.0

### What Skyrim version are you using?

1.6.1170

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AtomCrafty** [comment]
1.1.0 and 1.2.0 are both obsolete. This should be fixed in 2.0.0, but that's not on Nexus yet. The [canary build](https://github.com/MissCorruption/QuickLootIE/releases) is fairly stable and can be used, but some features aren't fully working yet.

**Comment by MissCorruption** [comment]
The canary build should work now without debug redistributables. Closing this issue as it has been fixed in canary.
