### ISSUE TITLE
Dll From Canary Build of v.2.0.0 Is Not Compatible With Skyrim GOG v.1.6.1179

### ISSUE THREAD

**Issue by LeavingUndad** [MissCorruption/QuickLootIE#39]
### What happened?

Unfortunately the *.dll from the pre-release Canary build of v.2.0.0 is not compatible with Skyrim GOG v.1.6.1179: starting the game gives me a warning about the *.dll incompatibility. Version 1.2.0 hadn't this issue though and worked for me just fine. Just wanted to bring it to your attention before you release the next stable version.

### Version

2.0.0-Canary

### What Skyrim version are you using?

Skyrim GOG v.1.6.1179

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MissCorruption** [comment]
Try updating your VC++ redistributables to the latest. We have at least one other person loading fine on 640

**Comment by LeavingUndad** [comment]
Sorry, but I've just updated the VC++ redistributable to the latest (Microsoft Visual C++ 2022 X64 - https://aka.ms/vs/17/release/vc_redist.x64.exe), but starting the game with the Canary build of QuicklootIE 2.0.0 installed still gives me a warning that the *.dll is not compatible. Are you referring to another build of VC++ redistributable? Besides I use Skyrim GOG v.1.6.1079, not v.1.6.640. Also I'm the same person who posted to your QuicklootIE mod's Posts section on Nexus that your stable version of the mod - v.1.2.0 - works fine (and it's true) in Skyrim GOG v.1.6.1079 - I'm Nibenon76. But unfortunately not the Canary build of QuicklootIE 2.0.0, despite all mod's requirements are installed and updated.

**Comment by LeavingUndad** [comment]
[AtomCrafty](https://github.com/AtomCrafty) found the culprit [here](https://github.com/MissCorruption/QuickLootIE/issues/43#issuecomment-2259114184).

**Comment by MissCorruption** [comment]
Try the latest release and report back. It should be fixed now

**Comment by LeavingUndad** [comment]
Yep, it's fixed now, thank you a lot! I was able to start the game without any incompatibility error warnings, successfully loaded my latest save and even tested the new version a bit.

It seems everything works as intended (owned items are correctly marked, useful Value/Weight rating - special thanks for that(!), etc). The only issue I've encountered so far is that the hotkey for the Search option is directly tied to the hotkey of the Favourites menu: pushing its default [Q] button brings the Favourites menu first, I have to close it with [Tab] button, only then it opens the container. Changing the hotkey for the Favourites menu to another button in game options automatically changes the Search hotkey to the same button. That's inconvenient and I hope it will be fixed in the next stable version.

Thank you again for the fix (and for the mod, of course)! I'll report back if encounter any other issue.

**Comment by AtomCrafty** [comment]
Huh, that is odd. It shouldn't open the favorites menu while the loot menu is open. That key event is supposed to be suppressed.

I've already brought up the topic of making the keys configurable instead of using the Favorites/Interact/Sheath keys. Gonna look into that when I tackle the rewrite of the input system.

**Comment by LeavingUndad** [comment]
@[AtomCrafty](https://github.com/AtomCrafty)
Thanks for looking into it!

I think the bug with *.dll may be closed now.
