### ISSUE TITLE
[Question/Bug]: Does 2.0.0 Canary not work with 1.5.97?

### ISSUE THREAD

**Issue by Xelphos** [MissCorruption/QuickLootIE#41]
### What happened?

I cannot get the canary version to function properly on 1.5.97. Version 1.2.0 from the Nexus works without issue, but with 2.0.0 only the MCM shows up, the actual loot menu does not appear when looking at containers.

Went a bit further and only loaded up with the absolute minimum. So only the mods QuickLoot IE requires plus Backported Extended ESL Support so the ESP loads on 1.5.97 and Alternative Perspective. MCM does appear, and seems to function just fine. Mod shows up as 1.2.1.0, and the DLL version does not appear in the MCM. So I am not sure.

### Version

1.2.0 - 2.0.0

### What Skyrim version are you using?

1.5.97

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MissCorruption** [comment]
Will need to investigate this at a later date, as I'm busy atm. Bit given multiple people reported it not working, I consider the report valid

**Comment by LeavingUndad** [comment]
[AtomCrafty](https://github.com/AtomCrafty) found the culprit [here](https://github.com/MissCorruption/QuickLootIE/issues/43#issuecomment-2259114184).

**Comment by MissCorruption** [comment]
TRy the latest canary release and report back, @LeavingUndad

**Comment by Xelphos** [comment]
> TRy the latest canary release and report back, @LeavingUndad and @Xelphos.
> 
> LeavingUndad has confirmed it works on GOG, I'll assume this as fixed, given it's the same issue.

Yep. It works. Thanks for the quick fix.
