### ISSUE TITLE
[FEATURE]: Disable loot menu while mounted and during KillCams

### ISSUE THREAD

**Issue by rheena211** [MissCorruption/QuickLootIE#42]
### Feature Title

Requesting option to disable the QuickLoot menu from opening while mounted and during KillCams

### Motivation

It seems unrealistic my character is able to loot containers from the back of a horse! It's a very minor request and not at all important. On the other hand, the fact that the QuickLoot menu opens after killing an enermy during a KillCam has always kinda "killed" ;) the moment and disabling it would look nicer cinematically (thinking of [this mod](https://www.nexusmods.com/skyrimspecialedition/mods/109457)).

### Feature Description

An option in the MCM menu to disable the QuickLoot menu from opening while mounted on a horse/other rideable creature and another option to disable the menu during KillCams.

**Comment by Wuerfelhusten** [comment]
I would add a ini setting or a MCM setting for mounted looting. I for myself really like the ability to loot from the back of horses.

**Comment by AtomCrafty** [comment]
I've implemented a check to disable the loot menu during kill cams and auto vanity mode (the spinning afk cam). Looks like mounts use a separate camera state, so implementing a toggle for mounted looting should be fairly straightforward.

**Comment by MissCorruption** [comment]
Fixed by #40

**Comment by MissCorruption** [comment]
Reopened to close this once settings are implemented

**Comment by AtomCrafty** [comment]
MCM settings are done.
