### ISSUE TITLE
[Bug]: Input keys are not surpressed properly at times

### ISSUE THREAD

**Issue by MissCorruption** [MissCorruption/QuickLootIE#45]
### What happened?

Two reports on Nexus indicate that the weapon sheath/unsheath key (R by default) is not properly suppressed, #39 indicates that the favorites key to search the container is also not suppressed properly.

### Version

2.0.0

### What Skyrim version are you using?

1.6.1170

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LeavingUndad** [comment]
In my game (Skyrim GOG v.1.6.1179, but I doubt it does matter here) it's not possible to get ready/stash away weapon(s)/spell(s) while QuickLootIE's menu is active. I.e. the game's default [R] hotkey IS completely suppressed in this case (although it may be inconvenient for some users). Unlike the game's default [Q] hotkey, which is indeed not suppressed at all, as I reported it in [#39](https://github.com/MissCorruption/QuickLootIE/issues/39).

**Comment by MissCorruption** [comment]
I personally have not been able to encounter any of these issues, which makes it harder to track/fix. It's very inconsistent.

Do you happen to have any mod changing the favorites menu in a way?

**Comment by LeavingUndad** [comment]
I see. Well, except SkyUI (of course) I also use [Extended Hotkey System (Anniversary Edition)](https://www.nexusmods.com/skyrimspecialedition/mods/32225), [Persistent Favorites](https://www.nexusmods.com/skyrimspecialedition/mods/118174) and [Favorite Misc Items](https://www.nexusmods.com/skyrimspecialedition/mods/42750). These are all the mods that directly edit the Favorites menu and I can think of off the top of my head. I hope it will help you to find the culprit.

**Comment by AtomCrafty** [comment]
If you have some free time, could you check whether the issue persists if you disable the mentioned mods? Might be a long shot, but if disabling them fixes the issue at least we know what to focus on.

**Comment by LeavingUndad** [comment]
@[AtomCrafty](https://github.com/AtomCrafty)
Sure, I should have figured this out myself earlier. Anyway it was super easy and I've found the culprit at once: it was [Extended Hotkey System](https://www.nexusmods.com/skyrimspecialedition/mods/32225)(Anniversary Edition), which is a pure SKSE mod by [Vermunds](https://www.nexusmods.com/skyrimspecialedition/users/26327049).

**Comment by AtomCrafty** [comment]
@MissCorruption do you think there is a chance that the R issue is also related to other mods? I haven't seen the Nexus reports. Regarding EHS: If it's still maintained we could ask the dev to add a check whether the loot menu is open.

**Comment by LeavingUndad** [comment]
Sorry, but why not just make the mod's hotkeys to be configurable in the MCM or in an *.ini file? Doing so would make the hotkey compatibility issues with other mods to be the problem of users, not yours. Is there any reason not to do so?

**Comment by MissCorruption** [comment]
> @MissCorruption do you think there is a chance that the R issue is also related to other mods? I haven't seen the Nexus reports. Regarding EHS: If it's still maintained we could ask the dev to add a check whether the loot menu is open.

The report on Nexus mentioned an incompatibility with another mod, ye. But it was entirely in Papyrus, it was [this](https://www.nexusmods.com/skyrimspecialedition/mods/3182) one

**Comment by MissCorruption** [comment]
Closing this in favor of #51
