### ISSUE TITLE
[FEATURE]: Dynamic Activation Key

### ISSUE THREAD

**Issue by TruePureGold** [MissCorruption/QuickLootIE#46]
### Feature Title

Use DAK

### Motivation

Easier addition of modifier key

### Feature Description

DAK would allow you to easily integrate a modifier key (shift) to change "take to "use" as you already plan to

### Additional Context

https://www.nexusmods.com/skyrimspecialedition/mods/96273
Mod link ^

**Comment by MissCorruption** [comment]
When discussing the feature we were considering DAK but ultimately decided to see if it would actually be easier if we implemented it ourselves. 

It's still a valid suggestion, so I'll leave this open.

**Comment by AtomCrafty** [comment]
I haven't looked into it too much, but I think DAK is primarily useful for Papyrus mods. We do plan to replicate the behavior, but it will need to all be implemented on our end.

**Comment by MissCorruption** [comment]
Closing this in favor of #51
