### ISSUE TITLE
[Bug]: Flickering when using Better Third Person Selection

### ISSUE THREAD

**Issue by Aphegor0112** [MissCorruption/QuickLootIE#49]
### What happened?

Like the title said, everything is normal when I'm in first person. But when in third person and using BTPS, it's just keep changing target selection between the loot and nearby object.

### Version

2.0.0

### What Skyrim version are you using?

1.6.1170

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AtomCrafty** [comment]
I believe this was fixed on the BTPS end and broke again because of the DLL rename. So I think it BTPS needs to be updated to fix this.

**Comment by MissCorruption** [comment]
Yes, the issue lies on BTPS' side and not ours. The author has been informed already. Until BTPS is updated you'll have flickering, renaming the DLL won't be supported by us
