### ISSUE TITLE
[FEATURE]: Make Value/Weight column as MCM option

### ISSUE THREAD

**Issue by CaptainRay1993** [MissCorruption/QuickLootIE#52]
### Feature Title

Make Value/Weight Optional

### Motivation

Maybe this is niche, Value/Weight info is convenient while feels too gamey to me.

**Comment by AtomCrafty** [comment]
It's on our todo list, but very low priority for now. Making the columns configurable will require another pretty major change to the swf, so we'll need to carefully consider how to approach this to not break compatibility with existing reskins.

**Comment by CaptainRay1993** [comment]
Sure. Just take your time.

**Comment by MissCorruption** [comment]
Breaking the LootMenu yet again is a rather unwelcoming choice imo

**Comment by AtomCrafty** [comment]
I think we can pull this off without breaking reskin compatibility.

**Comment by MissCorruption** [comment]
I wouldn't mark this as high prio for now, but we can look into it at some point

**Comment by MissCorruption** [comment]
Backend is done as per #40, MCM needs implementation still

**Comment by CaptainRay1993** [comment]
Awesome! Btw it would be best to swap the price and weight columns to be consistent with the inventory order.

**Comment by AtomCrafty** [comment]
When the MCM is done you'll be able to reorder them however you like.

**Comment by AtomCrafty** [comment]
This is implemented and will be included in the next release.
