### ISSUE TITLE
[FEATURE]: QuickLoot and Oblivion Interaction Icons

### ISSUE THREAD

**Issue by Sw33z3r** [MissCorruption/QuickLootIE#53]
### Feature Title

A way to use oblivion interaction icons without modifying the quickloot button text

### Motivation

I really like the Oblivion Interaction Icons but I don't think it looks good on Quickloot, is there any way to revert the icons back to text without uninstalling Oblivion Interaction Icons?

**Comment by AtomCrafty** [comment]
I don't think there is a straightforward way to achieve this. Afaik OII overwrites the translations for those strings, so the original text isn't even in the game anymore if you have it installed. So QuickLoot has no way of knowing what "Take" translates to in the player's language.

**Comment by Sw33z3r** [comment]
I understand, maybe just removing those changes in xEdit is the only way to solve this. thanks for the answer and thanks for the mod!

**Comment by MissCorruption** [comment]
This likely won't happen as to what Crafty said above. There are a lot of things to configure, but I don't see a real reason to do this.
