### ISSUE TITLE
[Bug]: Icons of Soul Stones are not displayed,

### ISSUE THREAD

**Issue by Neutral9** [MissCorruption/QuickLootIE#57]
### What happened?

Icons of Soul Stones are not displayed, other icons work fine, I understand that this is because they are vanilla icons that are not affected by the Inventory Interface Information Injector mod, so Quick Loot does not see them.

Also if the “Open when container is unlocked” setting is enabled, there will be no cursor when the inventory menu appears, you will have to re-enter the chest for the cursor to appear.

Also in your MCM menu there is a 4th empty item that can be clicked on, but there is nothing there and it is invisible, it is a small thing.

### Version

2.0.0

### What Skyrim version are you using?

1.5.97

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MissCorruption** [comment]
What mod wee you using for custom icons? In my testing with AIT and KIT they appeared fine.

As for the MCM option, I commented out a page since it's functionality wasn't implemented yet (sorting rules), but seemingly forgot to adjust the page count. Shouldn't cause any issues.

**Comment by MissCorruption** [comment]
Fixed with https://github.com/MissCorruption/QuickLootIE/commit/d52763a57611a36c7d6ee61f13840bd8ce516f78
