### ISSUE TITLE
[FEATURE]: Devious Enchanted Chests support

### ISSUE THREAD

**Issue by wolfeman77351** [MissCorruption/QuickLootIE#58]
### Feature Title

Devious Enchanted Chests Support

### Motivation

QuicklootIE breaks the core functionality of Devious Enchanted Chests, which is to spring a trap when opening various containers. 

### Feature Description

QuicklootIE bypasses the traditional method of opening containers. This feature/patch would restore functionality to Devious Enchanted Chests and other similar mods

### Additional Context

Im not a modder, so I do not know how it would be done, or if its an issue for the Devious Lore mod author.

**Comment by wolfeman77351** [comment]
https://www.loverslab.com/files/file/1405-deviously-enchanted-chests/

**Comment by AtomCrafty** [comment]
If I'm not mistaken, @AndbGame is working on a compatibility plugin over here https://github.com/AndbGame/QuickLootIE-DD, but I'm not sure whether it is done already. The necessary functionality on the QuickLoot side was already provided via #37.
