### ISSUE TITLE
[Bug]: Slight incompatibility with Simple Activate

### ISSUE THREAD

**Issue by MissCorruption** [MissCorruption/QuickLootIE#59]
### What happened?

When hovering over containers, QuickLoot (QL) causes Simple Activate (SA) to perform a momentary refresh. This is particularly noticeable when hovering over empty containers.

### Observed Behavior:
- The “empty” tag briefly appears and disappears.
- The container name briefly turns white before switching to grey, as per Simple Activate settings.

### Steps to Reproduce:
- Hover over an empty container.
- Observe the flickering of the "empty" tag and the container name color.

### Expected Behavior:
The container name should remain consistently grey (or follow the SA settings) without any brief visual changes during the hover action.

### Version

2.0.0

### What Skyrim version are you using?

1.6.1170

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MissCorruption** [comment]
SA's HUD handling seems to be done [here](https://github.com/powerof3/SimpleActivateSKSE/blob/master/src/Manager.cpp) for reference.

**Comment by MissCorruption** [comment]
Forwarding a report from Nexus, which is also related to Simply Activate:

> When used with Simple Activate SKSE
Everything else works the same
But activation key E doesn't disappear for locked containers
I used the option to make activation key E disappear in Simple Activate SKSE

> All experiments were done in vanilla state with minimal plugins
Just Address Library for SKSE Plugins, Simple Activate SKSE and QuickLoot IE
I was able to reliably observe that removing QuickLoot IE would normally remove the activation key 'E' from locked containers

>Needs patch

**Comment by AtomCrafty** [comment]
I have no idea what could be causing that new issue. We don't even touch the prompt unless the loot menu is open, which is never the case for locked containers.

**Comment by AtomCrafty** [comment]
I spent way too many hours trying to debug the flickering prompt (without SA) and it defines all logic. The HUD Menu never even gets instructed to show the prompt, but somehow it still does. I'm inclined to close this as won't fix because I literally have no idea how this even happens.

**Comment by MissCorruption** [comment]
If we're that clueless, we can close this as won't fix. The issue doesn't seem to be game breaking and I assume the lockpicking one might get fixed along the way. Closing this and won't fix and pinning it, if anyone has insides on this, go ahead.

**Comment by AtomCrafty** [comment]
I think I fixed this with https://github.com/AtomCrafty/QuickLootIE/commit/b66a4a4a2c8f2797b71ff45d95403c744397b2d7. At least this fixes the flickering prompt when looking away from a container. I was unable to produce any unwanted interaction with Simple Activate in this version.
