### ISSUE TITLE
[FEATURE]: Container Blacklist Capacity

### ISSUE THREAD

**Issue by AFROYuls** [MissCorruption/QuickLootIE#60]
### Feature Title

Container Blacklist Capacity

### Motivation

With a way to filter containers so quickloot menu doesn't show on specific containers, would allow mod authors to create compatibility patches.

### Feature Description

E.G.  "grave digging" swaps with Base Object Swapper the graves of the game so now you need a shovel to dig graves but a the moment quickloot menu show up in the graves allowing the player to loot without the need of a shovel.

So a way to blacklist containers with maybe an INI file and keywords would allow authors to exclude quickloot for certain contaniers.

**Comment by AtomCrafty** [comment]
Hmm, that should be fairly easy to implement.
