### ISSUE TITLE
[FEATURE]: Suppress container menu after lockpicking

### ISSUE THREAD

**Issue by AtomCrafty** [MissCorruption/QuickLootIE#62]
### Feature Title

Suppress container menu after lockpicking

### Feature Description

The MCM contains an option called "Open when container is unlocked," which currently doesn't do anything.
I think this should serve as a toggle between two behaviors when unlocking a container:

1. The regular container menu opens (vanilla behavior).
2. The container menu is suppressed and the loot menu opens instead.

The current behavior is always this, no matter the setting:

- Lockpick menu closes
- Loot menu opens
- Container menu opens after a moment, which causes the loot menu to close again

### Additional Context

Under the current implementation, the loot menu always shows because the lockpick menu close event causes a visibility refresh.

The desired behavior should be possible to implement by hooking the calls this mod overwrites with nop slides.
Gotta make sure to add a compatibility check so we don't crash trying to call 0x90909090.
https://github.com/Umgak/Skyrim-No-Lockpick-Activate/blob/master/src/main.cpp

**Comment by MissCorruption** [comment]
The PR has been merged, but there's a crash if No Lockpick Activate is installed

**Comment by AtomCrafty** [comment]
It's fixed in https://github.com/AtomCrafty/QuickLootIE/commit/962ec9a9581ddbb312bbf81932539f23e9a362bb, but that isn't in master yet.
