### ISSUE TITLE
[FEATURE]: Native support for Artifact Tracker

### ISSUE THREAD

**Issue by MissCorruption** [MissCorruption/QuickLootIE#67]
### Feature Title

Natively support the rather niche mod Artifact Tracker

### Motivation

We already support TCC and Artifact Tracker is the same but without LOTD, so it makes sense to also support it.

### Feature Description

Mod in question is hosted here: https://mod.pub/skyrim-se/36-artifact-tracker

**Comment by AtomCrafty** [comment]
Done
