### ISSUE TITLE
[FEATURE]: Native compatibility with Object Manipulation Overhaul

### ISSUE THREAD

**Issue by MissCorruption** [MissCorruption/QuickLootIE#68]
### Feature Title

Compatibility for OMO

### Motivation

Gotta be the best QuickLoot there ever was, eh?

### Feature Description

Manipulating a chest with OMO keeps the LootMenu active and thus makes it harder to use OMO with QLIE installed. Mod in question; https://www.nexusmods.com/skyrimspecialedition/mods/123664

**Comment by MissCorruption** [comment]
The author has been informed and advised to use our API and provide support from their side. Keeping this open until I get a reply.

**Comment by AtomCrafty** [comment]
I think we can close this since we now have keybindings to disable the loot menu entirely.

**Comment by MissCorruption** [comment]
Fair point, I'll close this.
