### ISSUE TITLE
[FEATURE]: Disable Item Icons

### ISSUE THREAD

**Issue by lolcatplays** [MissCorruption/QuickLootIE#69]
### Feature Title

Disable Item Icons

### Motivation

I want to make it look as stock as possible, to match FO4. Tried looking through options and can't seem to find a way to remove them.

**Comment by AtomCrafty** [comment]
It's possible, but requires another sfw change. Wouldn't break compatibility with older skins though, they just wouldn't support the toggle until they are updated.

**Comment by lolcatplays** [comment]
I hope you consider it for the next update, though breaking skins for a minor update might be a problem for everyone

**Comment by AtomCrafty** [comment]
It wouldn't break skins. They would work just fine, but ignore the new setting. That's what I was trying to say before ^^

Adding the option shouldn't be terribly difficult either. I doubt many players would use it, but it wouldn't be the most niche option we provide.

**Comment by MissCorruption** [comment]
Assuming you mean disabling the item icons entirely, that seems like a niche feature. We'll add it, but it's not high priority right now.

**Comment by AtomCrafty** [comment]
Implemented.
