### ISSUE TITLE
[Bug]: Warhammers use Battleaxe icon

### ISSUE THREAD

**Issue by Hexroid** [MissCorruption/QuickLootIE#71]
### What happened? (Actual vs Expected Behavior)

Warhammers use battleaxe icon. This happens in version 3.0.0 too

### Steps to Reproduce

Put a warhammer in a container, it has the battleaxe icon displayed on the Quickloot menu

### Version

2.0.0

### What Skyrim version are you using?

1.6.640

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MissCorruption** [comment]
Do battleaxes show a warhammer icon? The difference between the two is made using keywords, maybe something is messing with those?

**Comment by MissCorruption** [comment]
![image](https://github.com/user-attachments/assets/5e87bdf5-bab0-4f8a-9b2e-262c92c7fdeb)
I cannot reproduce it using Aura's Inventory Tweaks, both Warhammers and Battleaxes have the correct icons
