### ISSUE TITLE
[Bug]: Disable/Enable loot menu keys seem to be reversed

### ISSUE THREAD

**Issue by junip0r** [MissCorruption/QuickLootIE#73]
### What happened? (Actual vs Expected Behavior)

I have these keys set, using Shift as a modifier:
![image](https://github.com/user-attachments/assets/7e6fa88a-f4f7-4053-a7d5-57e2d69e3f2d)
However,

...when I press Shift and -, the menu is enabled.
...when I press Shift and +, the menu is disabled.

Additionally:

In the Controls MCM, when I mouse-over the `Modifier` entry for `Search`, I see this in the help area:

![image](https://github.com/user-attachments/assets/8b56b965-a879-46dc-82c3-5936acec73ea)

However when I mouse-over the `Modifier` entry for `Disable loot menu` or `Enable loot menu`, I see this:

![image](https://github.com/user-attachments/assets/2bb0aee2-b4bb-40aa-a4ab-d31f570ca5fd)
![image](https://github.com/user-attachments/assets/34f911e2-0c0a-4d82-b8cb-15d81db1f19f)

Additionally:

- Open MCM
- Select Controls
- Click `Modifier` for `Disable loot menu` or `Enable loot menu`
- The dialog opens but has no menu items.
![image](https://github.com/user-attachments/assets/3a6c9be9-f4e8-4e9c-911e-c44e143f2aab)
- If I select `Modifier` for `Search`, the dialog correctly displays the list of modifiers.
- If, after opening the `Modifier` dialog for `Search`, I then select `Modifier` for `Enable loot menu` or `Disable loot menu`, the dialog correctly displays the list of modifiers.
![image](https://github.com/user-attachments/assets/fd3b5944-3446-4ef6-a6c3-c9e4f1019951)
![image](https://github.com/user-attachments/assets/cbf84907-d25d-4471-935e-e294731420e7)

### Steps to Reproduce

Outlined in _Actual vs Expected Behavior_. Please let me know if you need any more details, or if you can't reproduce. Thanks! :)

### Version

3.0.0

### What Skyrim version are you using?

1.6.1170

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AtomCrafty** [comment]
Thanks for bringing that to my attention. The disable/enable keybindings were a last minute addition, so I seem to have missed a few things ^^
