### ISSUE TITLE
[Bug]: Loot notification about FormID outside the valid range

### ISSUE THREAD

**Issue by cultab** [MissCorruption/QuickLootIE#79]
### What happened? (Actual vs Expected Behavior)

LOOT gives the following notification:

--------------------

QuickLootIE.esp contains records that have FormIDs outside the valid range for an ESL plugin. Using this plugin will cause irreversible damage to your game saves.

The valid FormID range for ESL plugins is FExxx800-FExxxFFF in Skyrim Special Edition and FExxx001-FExxxFFF in Fallout 4. If this plugin was uploaded in this state, the error should be reported to the author.

--------------------

# Is this expected? Can it be ignored? Or is it a genuine issue?

### Steps to Reproduce

Install with MO2 and activate LOOT notifications.

### Version

3.0.0

### What Skyrim version are you using?

doesn't matter

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MissCorruption** [comment]
With the 1.6.1130 update Bethesda extended the range of ESL plugins by fixing a bug that caused them to require starting at 0x800. Either update LOOT, or ignore the warning. If you're on a version lower than 1.6.1130 you need to have [BEES](https://www.nexusmods.com/skyrimspecialedition/mods/106441) installed.
