### ISSUE TITLE
[Feat.] - Add keyword integration to the lootmenu

### ISSUE THREAD

**Issue by MissCorruption** [MissCorruption/QuickLootIE#9]
Currently KIT, AIT and any i4 mod using keywords to distribute icons doesn't work. Adding support for keywords in the lootmenu should fix it

**Comment by MissCorruption** [comment]
Progress on this was made with #24 however some icons are not appearing still

**Comment by MissCorruption** [comment]
# Attributes we need to implement

## Books
- **formType**
- **bookType**
- **keywords**
- **subType**

## Ingestibles
- **formType**
- **keywords**
- **subType**
- **archetype**
- **actorValue**

## Ingredients
- **formType**
- **keywords**

## Keys
- **formType**
- **keywords**

## Light
- **formType**
- **formId**

## Misc
- **formType**
- **keywords**
- **formId**

## Scrolls
- **formType**
- **school**
- **keywords**

## Soul Gems
- **formType**
- **keywords**
- **status**

## Weapons
- **formType**
- **keywords**
- **subType**
- **isEnchanted**

## Ammo
- **formType**
- **keywords**

## Spells
- **formType**
- **castType**
- **deliveryType**
- **school**
- **spellType**
- **formId**
- **iconColor**
- **archetype**
- **effectKeywords**
- **resistance**

## Shouts
- **formId**

## Various Things
- **equipSlot**
- **formType**
- **keywords**
- **duration**
- **resistance**

**Comment by MissCorruption** [comment]
Currently, all armors show as helmets and letters show the book icon instead of the notes icon. Additionally, colors are not present.

**Comment by AtomCrafty** [comment]
Colors will need to be implemented in ActionScript.

**Comment by MissCorruption** [comment]
This has been implemented and merged into master.
